---

- name: Change user password
  hosts: 172.16.140.2

  # become: Run operations with become (does not imply password prompting)
  # If you need to ask for privilege escalation password, use --ask-become-pass
  become: true

  # gather_facts: Gathers facts about remote hosts
  #               (equivalent to ansible.builtin.setup module)
  gather_facts: no


  vars:
    username:                 "berezinve"
    password:                 "berezinve"
    # uid:                    "1005"
    #ansible_become_password: "berezinve"


  tasks:
  - name: 1 - Changing password of '{{ username }}' user
    user:
     name: '{{ username }}'
     password: "{{ password | password_hash('sha512') }}"

     # update_password: always - will update passwords if they differ.
     # update_password: on_create - will only set the password for newly created users.
     update_password: always

     # Whether the account should exist or not, taking action if the state is different
     # from what is stated.
     state: present
