---

- name: Install apache and upload my web page
#  hosts: staging_servers
  hosts: 192.168.1.130
  become: true


  vars:
    source_file:       ./MyWebSite/index.html
    destination_file:  /var/www/html


  tasks:

  - name: Check and print OS version
    debug: var=ansible_os_family


  - block:   #========= Block for RedHat =========#

      - name: Install Apache Web Server for RedHat
        yum:  name=httpd state=latest

      - name: Copy ./MyWebSite/index.html to remote hosts
        copy: src={{ source_file }} dest={{ destination_file }} mode=0555
        notify: Restart Apache RedHat

      - name: Start httpd service for RedHat and enable it on every boot
        service:  name=httpd state=started enabled=true

    when: ansible_os_family == "RedHat"


  - block:   #========= Block for Debian =========#

      - name: Install Apache Web Server for Debian
        apt:  name=apache2 state=latest

      - name: Copy ./MyWebSite/index.html to remote hosts
        copy: src={{ source_file }} dest={{ destination_file }} mode=0555
        notify: Restart Apache Astra Linux

      - name: Start apache2 service for Debian and enable it on every boot
        service:  name=apache2 state=started enabled=true

    when: ansible_os_family == "Astra Linux"


  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Astra Linux
    service: name=apache2 state=restarted
