---
- name: Stop docker containers
  hosts: staging_servers
  become: true


  tasks:

    - name: Get info on docker host and list images
      docker_host_info:
        containers: yes
      register: containers_to_stop
    - name: Stop running docker containers
      docker_container:
        name: '{{ item.Names.0[1:] }}'
        image: '{{ item.Image }}'
        state: stopped
      loop: '{{ containers_to_stop.containers }}'
