---
# handlers file for deploy_apache_web

- name: Restart nginx RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart nginx Astra Linux
  service: name=nginx state=restarted
  when: ansible_os_family == "Astra Linux"
